/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingRouteImport } from './routes/admin/booking'
import { Route as AdminCafeRouteImport } from './routes/admin/cafe'
import { Route as AdminGamesRouteImport } from './routes/admin/games'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminSettingRouteImport } from './routes/admin/setting'
import { Route as AdminTournamentRouteImport } from './routes/admin/tournament'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingRoute = AdminBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCafeRoute = AdminCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingRoute = AdminSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTournamentRoute = AdminTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/setting': typeof AdminSettingRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/setting': typeof AdminSettingRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/setting': typeof AdminSettingRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/login'
    | '/signup'
    | '/admin/booking'
    | '/admin/cafe'
    | '/admin/games'
    | '/admin/login'
    | '/admin/members'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/setting'
    | '/admin/tournament'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/signup'
    | '/admin/booking'
    | '/admin/cafe'
    | '/admin/games'
    | '/admin/login'
    | '/admin/members'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/setting'
    | '/admin/tournament'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/login'
    | '/signup'
    | '/admin/booking'
    | '/admin/cafe'
    | '/admin/games'
    | '/admin/login'
    | '/admin/members'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/setting'
    | '/admin/tournament'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/booking': {
      id: '/admin/booking'
      path: '/booking'
      fullPath: '/admin/booking'
      preLoaderRoute: typeof AdminBookingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cafe': {
      id: '/admin/cafe'
      path: '/cafe'
      fullPath: '/admin/cafe'
      preLoaderRoute: typeof AdminCafeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setting': {
      id: '/admin/setting'
      path: '/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof AdminSettingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tournament': {
      id: '/admin/tournament'
      path: '/tournament'
      fullPath: '/admin/tournament'
      preLoaderRoute: typeof AdminTournamentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingRoute: typeof AdminBookingRoute
  AdminCafeRoute: typeof AdminCafeRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingRoute: typeof AdminSettingRoute
  AdminTournamentRoute: typeof AdminTournamentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingRoute: AdminBookingRoute,
  AdminCafeRoute: AdminCafeRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingRoute: AdminSettingRoute,
  AdminTournamentRoute: AdminTournamentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
